# Generated by Django 4.1.5 on 2023-01-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='super_type',
        ),
    ]
