# Generated by Django 4.1.5 on 2023-01-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_remove_super_super_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super',
            new_name='Supers',
        ),
    ]
